#!/bin/bash

printHelp(){
    echo "-r    -rhy    Exact Rhymes"
    echo "-n    -nry    Near Rhymes"
    echo "-s    -syn    Synonyms"
    echo "-a    -ant    Antonyms"
    echo "-t    -trg    Triggers"
    echo "-hm   -hom    Homopones"
    echo "-c    -cns    Consonant Matches"
    echo "-h    --help  Print Help"
}

getQuery(){
    query="$1"
    if [ "$#" -gt 1 ]
    then
	for var in "${@:2}"
        do
            query="$query+$var"
        done
    fi
}

if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
    printHelp
elif [ "$1" = "-r" ] || [ "$1" = "-rhy" ]
then
    getQuery "${@:2}"
    curl https://api.datamuse.com/words\?rel_rhy\="$query" | jq | less
elif [ "$1" = "-n" ] || [ "$1" = "-nry" ]
then
    getQuery "${@:2}"
    curl https://api.datamuse.com/words\?rel_nry\="$query" | jq | less
elif [ "$1" = "-s" ] || [ "$1" = "-syn" ]
then
    getQuery "${@:2}"
    curl https://api.datamuse.com/words\?rel_syn\="$query" | jq | less
elif [ "$1" = "-a" ] || [ "$1" = "-ant" ]
then
    getQuery "${@:2}"
    curl https://api.datamuse.com/words\?rel_ant\="$query" | jq | less
elif [ "$1" = "-t" ] || [ "$1" = "-trg" ]
then
    getQuery "${@:2}"
    curl https://api.datamuse.com/words\?rel_trg\="$query" | jq | less
elif [ "$1" = "-hm" ] || [ "$1" = "-hom" ]
then
    getQuery "${@:2}"
    curl https://api.datamuse.com/words\?rel_hom\="$query" | jq | less
elif [ "$1" = "-c" ] || [ "$1" = "-cns" ]
then
    getQuery "${@:2}"
    curl https://api.datamuse.com/words\?rel_cns\="$query" | jq | less
else
    getQuery "$@"
    curl https://api.datamuse.com/words\?rel_rhy\="$query" | jq | less
fi
